"""eCCLIX search profiles for day-pass bulk extraction."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

SearchModule = Literal["instruments", "delinquent_tax", "securities", "combination_party"]


@dataclass(frozen=True)
class EcclixSearchProfile:
    key: str
    module: SearchModule
    instrument_type: str = ""
    days_back: int = 60
    days_back_end: int | None = None  # for historical window
    drill_summary: bool = False  # click LP/89 to open detail grid
    tax_year: int | None = None
    party_filter: str = ""  # securities city filter
    max_rows: int = 40
    priority: int = 1  # lower = run first
    filter_tags: tuple[str, ...] = ()  # ecclix_row_filters.apply_filters
    min_tax_due: float = 0
    download_if_pass: bool = False  # PDF only when filters pass


# Ordered sprint for 24h day pass (Scott/Bourbon on eCCLIX)
DAY_PASS_SPRINT: tuple[EcclixSearchProfile, ...] = (
    EcclixSearchProfile(
        key="lp_recent",
        module="instruments",
        instrument_type="LP",
        days_back=60,
        drill_summary=True,
        max_rows=50,
        priority=1,
    ),
    EcclixSearchProfile(
        key="lp_historical",
        module="instruments",
        instrument_type="LP",
        days_back=730,
        days_back_end=60,
        drill_summary=True,
        max_rows=30,
        priority=2,
    ),
    EcclixSearchProfile(
        key="delinquent_tax",
        module="delinquent_tax",
        tax_year=2025,
        max_rows=100,
        priority=3,
    ),
    EcclixSearchProfile(
        key="jlien",
        module="instruments",
        instrument_type="JLIEN",
        days_back=730,
        drill_summary=True,
        max_rows=25,
        priority=4,
    ),
    EcclixSearchProfile(
        key="tlien",
        module="instruments",
        instrument_type="TLIEN",
        days_back=365,
        drill_summary=True,
        max_rows=25,
        priority=5,
    ),
    EcclixSearchProfile(
        key="deed_estate",
        module="instruments",
        instrument_type="DEED",
        days_back=90,
        drill_summary=False,
        max_rows=20,
        priority=6,
    ),
    EcclixSearchProfile(
        key="securities_city_lien",
        module="securities",
        instrument_type="LIEN",
        days_back=365,
        party_filter="GEORGETOWN",
        max_rows=25,
        priority=7,
    ),
)

LP_RECENT_ONLY = (DAY_PASS_SPRINT[0],)

# Aggressive 1-day pass — paginate grids, minimal row caps
FULL_DAY_PASS_SPRINT: tuple[EcclixSearchProfile, ...] = (
    EcclixSearchProfile(
        key="delinquent_tax_full",
        module="delinquent_tax",
        tax_year=2025,
        max_rows=9999,
        priority=1,
    ),
    EcclixSearchProfile(
        key="lp_recent_full",
        module="instruments",
        instrument_type="LP",
        days_back=120,
        drill_summary=True,
        max_rows=9999,
        priority=2,
    ),
    EcclixSearchProfile(
        key="lp_historical_full",
        module="instruments",
        instrument_type="LP",
        days_back=730,
        days_back_end=120,
        drill_summary=True,
        max_rows=9999,
        priority=3,
    ),
    EcclixSearchProfile(
        key="mtg_recent",
        module="instruments",
        instrument_type="MTG",
        days_back=90,
        drill_summary=True,
        max_rows=9999,
        priority=4,
    ),
    EcclixSearchProfile(
        key="will_recent",
        module="instruments",
        instrument_type="WILL",
        days_back=365,
        drill_summary=True,
        max_rows=9999,
        priority=5,
    ),
    EcclixSearchProfile(
        key="jlien_full",
        module="instruments",
        instrument_type="JLIEN",
        days_back=730,
        drill_summary=True,
        max_rows=9999,
        priority=6,
    ),
    EcclixSearchProfile(
        key="tlien_full",
        module="instruments",
        instrument_type="TLIEN",
        days_back=730,
        drill_summary=True,
        max_rows=9999,
        priority=7,
    ),
    EcclixSearchProfile(
        key="glien_full",
        module="instruments",
        instrument_type="GLIEN",
        days_back=730,
        drill_summary=True,
        max_rows=9999,
        priority=8,
    ),
    EcclixSearchProfile(
        key="mlien_full",
        module="instruments",
        instrument_type="MLIEN",
        days_back=365,
        drill_summary=True,
        max_rows=9999,
        priority=9,
    ),
    EcclixSearchProfile(
        key="deed_recent",
        module="instruments",
        instrument_type="DEED",
        days_back=120,
        drill_summary=True,
        max_rows=9999,
        priority=10,
    ),
    EcclixSearchProfile(
        key="securities_city_lien",
        module="securities",
        instrument_type="LIEN",
        days_back=730,
        max_rows=9999,
        priority=11,
    ),
)

WHOLESALE_INSTRUMENT_PRIORITY = ("LP", "DEED", "MTG", "WILL", "REL", "MLIEN", "FLIEN")

# Operator signal stack — all LP + probate + code liens (email digest / skip trace)
SIGNAL_INTEL_SEARCH: tuple[EcclixSearchProfile, ...] = (
    EcclixSearchProfile(
        key="all_lp_recent",
        module="instruments",
        instrument_type="LP",
        days_back=365,
        drill_summary=True,
        max_rows=9999,
        priority=1,
    ),
    EcclixSearchProfile(
        key="all_lp_historical",
        module="instruments",
        instrument_type="LP",
        days_back=1825,
        days_back_end=365,
        drill_summary=True,
        max_rows=9999,
        priority=2,
    ),
    EcclixSearchProfile(
        key="will_probate",
        module="instruments",
        instrument_type="WILL",
        days_back=730,
        drill_summary=True,
        max_rows=9999,
        priority=3,
    ),
    EcclixSearchProfile(
        key="deed_estate",
        module="instruments",
        instrument_type="DEED",
        days_back=365,
        drill_summary=True,
        max_rows=9999,
        priority=4,
        filter_tags=("estate_deed", "big_home_signal"),
    ),
    EcclixSearchProfile(
        key="securities_code_georgetown",
        module="securities",
        instrument_type="LIEN",
        days_back=730,
        party_filter="GEORGETOWN",
        max_rows=9999,
        priority=5,
        filter_tags=("city_lien",),
    ),
    EcclixSearchProfile(
        key="securities_code_versailles",
        module="securities",
        instrument_type="LIEN",
        days_back=730,
        party_filter="VERSAILLES",
        max_rows=9999,
        priority=6,
        filter_tags=("city_lien",),
    ),
    EcclixSearchProfile(
        key="jlien_judgment",
        module="instruments",
        instrument_type="JLIEN",
        days_back=730,
        drill_summary=True,
        max_rows=9999,
        priority=7,
    ),
    EcclixSearchProfile(
        key="mlien_mechanics",
        module="instruments",
        instrument_type="MLIEN",
        days_back=730,
        drill_summary=True,
        max_rows=9999,
        priority=8,
    ),
)

# Deep portal search — every menu path you'd click on a day pass, with smart filters.
DEEP_PORTAL_SEARCH: tuple[EcclixSearchProfile, ...] = (
    EcclixSearchProfile(
        key="tax_human_big",
        module="delinquent_tax",
        tax_year=2025,
        max_rows=9999,
        priority=1,
        filter_tags=("human_owner_only", "street_address", "min_tax_500"),
        min_tax_due=500,
    ),
    EcclixSearchProfile(
        key="lp_recent_bank",
        module="instruments",
        instrument_type="LP",
        days_back=120,
        drill_summary=True,
        max_rows=9999,
        priority=2,
        filter_tags=("foreclosure_lp", "bank_counterparty", "any_distress"),
        download_if_pass=True,
    ),
    EcclixSearchProfile(
        key="lp_divorce_domestic",
        module="instruments",
        instrument_type="LP",
        days_back=365,
        drill_summary=True,
        max_rows=9999,
        priority=3,
        filter_tags=("divorce_domestic", "big_home_signal"),
        download_if_pass=True,
    ),
    EcclixSearchProfile(
        key="lp_premium_subdivision",
        module="instruments",
        instrument_type="LP",
        days_back=180,
        drill_summary=True,
        max_rows=9999,
        priority=4,
        filter_tags=("premium_subdivision", "any_distress"),
        download_if_pass=True,
    ),
    EcclixSearchProfile(
        key="mtg_recent",
        module="instruments",
        instrument_type="MTG",
        days_back=90,
        drill_summary=True,
        max_rows=9999,
        priority=5,
        filter_tags=("big_home_signal",),
    ),
    EcclixSearchProfile(
        key="will_estate",
        module="instruments",
        instrument_type="WILL",
        days_back=365,
        drill_summary=True,
        max_rows=9999,
        priority=6,
        filter_tags=("estate_deed", "human_owner_only"),
        download_if_pass=True,
    ),
    EcclixSearchProfile(
        key="deed_estate",
        module="instruments",
        instrument_type="DEED",
        days_back=180,
        drill_summary=True,
        max_rows=9999,
        priority=7,
        filter_tags=("estate_deed", "big_home_signal"),
        download_if_pass=True,
    ),
    EcclixSearchProfile(
        key="mlien_mechanics",
        module="instruments",
        instrument_type="MLIEN",
        days_back=730,
        drill_summary=True,
        max_rows=9999,
        priority=8,
        filter_tags=("any_distress",),
        download_if_pass=True,
    ),
    EcclixSearchProfile(
        key="flien_federal",
        module="instruments",
        instrument_type="FLIEN",
        days_back=730,
        drill_summary=True,
        max_rows=9999,
        priority=9,
        filter_tags=("any_distress",),
    ),
    EcclixSearchProfile(
        key="slien_state",
        module="instruments",
        instrument_type="SLIEN",
        days_back=730,
        drill_summary=True,
        max_rows=9999,
        priority=10,
        filter_tags=("any_distress",),
    ),
    EcclixSearchProfile(
        key="encumbrance",
        module="instruments",
        instrument_type="ENC",
        days_back=365,
        drill_summary=True,
        max_rows=9999,
        priority=11,
        filter_tags=("big_home_signal", "any_distress"),
    ),
    EcclixSearchProfile(
        key="release_recent",
        module="instruments",
        instrument_type="REL",
        days_back=90,
        drill_summary=True,
        max_rows=200,
        priority=12,
    ),
    EcclixSearchProfile(
        key="securities_georgetown_lien",
        module="securities",
        instrument_type="LIEN",
        days_back=730,
        party_filter="GEORGETOWN",
        max_rows=9999,
        priority=13,
        filter_tags=("city_lien", "any_distress"),
        download_if_pass=True,
    ),
    EcclixSearchProfile(
        key="securities_versailles_lien",
        module="securities",
        instrument_type="LIEN",
        days_back=730,
        party_filter="VERSAILLES",
        max_rows=9999,
        priority=14,
        filter_tags=("city_lien",),
    ),
    EcclixSearchProfile(
        key="jlien_judgment",
        module="instruments",
        instrument_type="JLIEN",
        days_back=730,
        drill_summary=True,
        max_rows=9999,
        priority=15,
        filter_tags=("any_distress",),
        download_if_pass=True,
    ),
    EcclixSearchProfile(
        key="tlien_tax_lien",
        module="instruments",
        instrument_type="TLIEN",
        days_back=730,
        drill_summary=True,
        max_rows=9999,
        priority=16,
        filter_tags=("any_distress",),
    ),
)

# Reliable day-pass order: tax grid first (always works), then instruments with login guards.
USABLE_EXTRACT: tuple[EcclixSearchProfile, ...] = (
    EcclixSearchProfile(
        key="tax_all",
        module="delinquent_tax",
        tax_year=2025,
        max_rows=9999,
        priority=1,
    ),
    EcclixSearchProfile(
        key="lp_year",
        module="instruments",
        instrument_type="LP",
        days_back=365,
        drill_summary=True,
        max_rows=9999,
        priority=2,
        filter_tags=("any_distress",),
    ),
    EcclixSearchProfile(
        key="will_estate",
        module="instruments",
        instrument_type="WILL",
        days_back=730,
        drill_summary=True,
        max_rows=9999,
        priority=3,
        filter_tags=("estate_deed", "human_owner_only"),
    ),
    EcclixSearchProfile(
        key="jlien",
        module="instruments",
        instrument_type="JLIEN",
        days_back=730,
        drill_summary=True,
        max_rows=9999,
        priority=4,
        filter_tags=("any_distress",),
    ),
    EcclixSearchProfile(
        key="securities_georgetown",
        module="securities",
        instrument_type="LIEN",
        days_back=730,
        party_filter="GEORGETOWN",
        max_rows=9999,
        priority=5,
        filter_tags=("city_lien",),
    ),
    EcclixSearchProfile(
        key="securities_versailles",
        module="securities",
        instrument_type="LIEN",
        days_back=730,
        party_filter="VERSAILLES",
        max_rows=9999,
        priority=6,
        filter_tags=("city_lien",),
    ),
)
